title:               Women in Mathematics
tagline:             'at the Ruhr-Universität Bochum'
description:         'A group for women and gender minorities in mathematics at the Ruhr-Universität Bochum.'
show_downloads: true
theme: jekyll-theme-cayman