title:               Women in Mathematics
tagline:             'at RUB'
description:         'A group for women and gender minorities in mathematics at RUB.'
show_downloads: true
theme: jekyll-theme-cayman